/* assets-bridge.js — single source of truth for everything we load from `assets/`.
 *
 * The `assets/` folder ships a real Wondershare Filmora 14 install. Most of it is
 * native Qt / Windows binaries we can't load in the browser, but a meaningful slice
 * IS plain SVG / PNG / TTF / JSON / XML that we can ship directly into the UI:
 *
 *   • 287 TTF/OTF fonts          → `assets/Fonts/`        (text panel font picker)
 *   • ~100 caption animations    → `assets/resources/captions/{Base,AnimationWithGUID,Motion}/`
 *   • 15 caption textures        → `assets/Captions/Texttures/TexturePreset/`
 *   • Filmora skin JSON palettes → `assets/Skin/filmora_{dark,light}.txt` (theme presets)
 *   • User manifests             → `assets/shapes/manifest.json`,
 *                                  `assets/transitions/manifest.json`
 *
 * Browsers can't list directories — so every URL below is enumerated up front. The
 * lists below were generated by `ls assets/...` and pinned here. */

const BASE = "assets/";

/* ---------------- curated font catalog (sourced from assets/Fonts/) --------------- */
/* Curated to ~250 commonly-used families. "All" exposes the full list. */
const FONT_FILES = [
  // Bebas Neue (8 weights)
  "Bebas Neue.ttf", "BebasNeue Bold.otf", "BebasNeue Bold.ttf", "BebasNeue Book.otf",
  "BebasNeue Book.ttf", "BebasNeue Light.otf", "BebasNeue Light.ttf", "BebasNeue Regular.otf",
  "BebasNeue Regular.ttf", "BebasNeue Thin.otf", "BebasNeue Thin.ttf",
  // Montserrat (12 weights)
  "Montserrat-Black.otf", "Montserrat-Bold.otf", "Montserrat-Bold.ttf",
  "Montserrat-ExtraBold.ttf", "Montserrat-ExtraBoldItalic.ttf", "Montserrat-ExtraLight.ttf",
  "Montserrat-Italic.ttf", "Montserrat-Light.otf", "Montserrat-Medium.otf", "Montserrat-Medium.ttf",
  "Montserrat-Regular.ttf", "Montserrat-SemiBold.ttf", "Montserrat-Thin.ttf",
  "16378902_Montserrat Black Italic.ttf", "16466454_Montserrat Black.ttf",
  // Roboto (full family)
  "Roboto-Black.ttf", "Roboto-BlackItalic.ttf", "Roboto-Bold.ttf", "Roboto-BoldCondensed.ttf",
  "Roboto-BoldCondensedItalic.ttf", "Roboto-BoldItalic.ttf", "Roboto-Condensed.ttf",
  "Roboto-CondensedItalic.ttf", "Roboto-Italic.ttf", "Roboto-Light.ttf", "Roboto-LightItalic.ttf",
  "Roboto-Medium.ttf", "Roboto-MediumItalic.ttf", "Roboto-Regular.ttf", "Roboto-Thin.ttf",
  "Roboto-ThinItalic.ttf", "RobotoCondensed-Bold.ttf", "RobotoCondensed-BoldItalic.ttf",
  "RobotoCondensed-Italic.ttf", "RobotoCondensed-Light.ttf", "RobotoCondensed-LightItalic.ttf",
  "RobotoCondensed-Regular.ttf", "RobotoSlab-Bold.ttf", "RobotoSlab-Light.ttf",
  "RobotoSlab-Regular.ttf", "RobotoSlab-Thin.ttf",
  // Open Sans
  "OpenSans-Bold.ttf", "OpenSans-BoldItalic.ttf", "OpenSans-ExtraBold.ttf", "OpenSans-ExtraBoldItalic.ttf",
  "OpenSans-Italic.ttf", "OpenSans-Light.ttf", "OpenSans-LightItalic.ttf", "OpenSans-Regular.ttf",
  "OpenSans-Semibold.ttf", "OpenSans-SemiboldItalic.ttf", "16485114_Open Sans ExtraBold.ttf",
  // Raleway (full family)
  "Raleway-Black.ttf", "Raleway-BlackItalic.ttf", "Raleway-Bold.ttf", "Raleway-BoldItalic.ttf",
  "Raleway-ExtraBold.ttf", "Raleway-ExtraBoldItalic.ttf", "Raleway-ExtraLight.ttf",
  "Raleway-ExtraLightItalic.ttf", "Raleway-Italic.ttf", "Raleway-Light.ttf", "Raleway-LightItalic.ttf",
  "Raleway-Medium.ttf", "Raleway-MediumItalic.ttf", "Raleway-Regular.ttf", "Raleway-SemiBold.ttf",
  "Raleway-SemiBoldItalic.ttf", "Raleway-Thin.ttf", "Raleway-ThinItalic.ttf",
  // Noto
  "NotoSans-Bold.ttf", "NotoSans-BoldItalic.ttf", "NotoSans-Italic.ttf", "NotoSans-Regular.ttf",
  "NotoSansJP-Regular.otf", "NotoSerif-Bold.ttf", "NotoSerif-BoldItalic.ttf", "NotoSerif-Italic.ttf",
  "NotoSerif-Regular.ttf", "NotoSerifJP-Regular.otf", "16435810_Noto Sans Black.ttf",
  // Display + branding
  "AbrilFatface-Regular.otf", "AbrilFatface-Regular.ttf", "Anton-Regular.ttf", "2047008_Anton Regular.ttf",
  "ArchivoBlack-Regular.ttf", "16463930_Archivo Black.ttf",
  "Archivo_ExtraCondensed-ExtraBold.ttf", "BowlbyOne-Regular.ttf", "Bungee-Regular.ttf",
  "BungeeInline-Regular.ttf", "Bangers-Regular.ttf", "16485062_Bangers Regular.ttf",
  "Cookie-Regular.ttf", "Damion-Regular.ttf", "DMSerifDisplay-Regular.ttf",
  "16433458_Barlow Condensed Bold.ttf", "Barlow-Black.ttf", "Barlow-Bold.ttf",
  "BarlowCondensed-Bold.ttf", "BarlowCondensed-Regular.ttf",
  "16433982_DM Sans Black.ttf", "16484278_Crimson Pro Black.ttf",
  "16378006_Crimson Text SemiBold.ttf",
  "AlfaSlabOne-Regular.ttf", "Allan-Regular.ttf",
  "Caprasimo-Regular.ttf", "16378898_Caprasimo Regular.ttf",
  "CarterOne-Regular.ttf", "Caveat-Bold.ttf", "Caveat-Regular.ttf", "CaveatBrush-Regular.ttf",
  "CedarvilleCursive-Regular.ttf", "ChelseaMarket-Regular.ttf", "Cinzel-Regular.ttf",
  "Chewy-Regular.ttf", "CoveredByYourGrace.ttf", "Elsie-Regular.ttf", "EmilysCandy-Regular.ttf",
  "Federo-Regular.ttf", "Flamenco-Regular.ttf", "FugazOne-Regular.ttf",
  "GochiHand-Regular.ttf", "2043092_Gochi Hand.ttf", "Graduate-Regular.ttf",
  "GreatVibes-Regular.ttf", "HomemadeApple-Regular.ttf", "JosefinSans-Light.ttf",
  "Jost-ExtraBold.ttf", "Jost-Regular.ttf", "Kalam-Light.ttf", "Kalam-Regular.ttf",
  "Knewave-Regular.ttf", "KumarOne-Regular.ttf",
  "Lato-Black.ttf", "Lato-Bold.ttf", "Lato-Regular.ttf", "LeckerliOne-Regular.otf",
  "LeckerliOne-Regular.ttf", "LibreBaskerville-Regular.ttf",
  "LibreFranklin-BlackItalic.ttf", "LibreFranklin-BoldItalic.ttf", "LibreFranklin-Italic.ttf",
  "LilitaOne-Regular.ttf", "Molle-Regular.ttf",
  "MrDafoe-Regular.ttf", "Pacifico-Regular.ttf", "PatuaOne-Regular.ttf",
  "PermanentMarker-Regular.ttf", "2039172_Permanent Marker Regular.ttf",
  "PetitFormalScript-Regular.ttf",
  "PlayfairDisplay-Black.otf", "PlayfairDisplay-Regular.otf",
  "Poppins-Bold.ttf", "Poppins-Light.ttf", "Poppins-Medium.ttf", "Poppins-Regular.ttf",
  "PressStart2P-Regular.ttf", "Quantico-Regular.ttf", "RozhaOne-Regular.ttf", "RussoOne-Regular.ttf",
  "Sacramento-Regular.ttf", "Satisfy-Regular.ttf", "ShadowsIntoLight-Regular.ttf", "SigmarOne-Regular.ttf",
  "SixCaps-Regular.ttf", "Sriracha-Regular.ttf", "StintUltraExpanded-Regular.ttf",
  "Teko-Bold.ttf", "Teko-Light.ttf", "Teko-Medium.ttf", "Teko-Regular.ttf", "Teko-SemiBold.ttf",
  "15013642_Tilt Warp Regular.ttf", "14958430_ZY Oliver.ttf",
  "Ultra.ttf", "VampiroOne-Regular.ttf", "VastShadow-Regular.ttf",
  "Yantramanav-Black.ttf", "Yellowtail-Regular.otf", "Yellowtail-Regular.ttf",
  "Zeyada.ttf", "AmaticSC-Bold.ttf", "OUTFIT-SEMIBOLD.TTF", "LuckiestGuy-Regular.ttf",
  "1976462_Luckiest Guy Regular.ttf",
  "Oswald-ExtraLight.ttf", "Oswald-Light.ttf", "Oswald-SemiBold.ttf",
  "Quicksand-Bold.otf", "Quicksand-BoldItalic.otf", "Quicksand-Italic.otf", "Quicksand-Light.otf",
  "Quicksand-LightItalic.otf", "Quicksand-Regular.otf", "Quicksand-Regular.ttf",
  "Exo-Black.otf", "Exo-Bold.otf", "Exo-ExtraBold.otf", "Exo-ExtraLight.otf", "Exo-Italic.otf",
  "Exo-Light.otf", "Exo-Medium.otf", "Exo-Regular.otf", "Exo-SemiBold.otf", "Exo-Thin.otf",
  "CormorantInfant-BoldItalic.ttf", "CormorantInfant-Medium.ttf", "CormorantInfant-MediumItalic.ttf",
  "DancingScript-Bold.ttf", "DancingScript-VariableFont_wght.ttf",
  "1906026_Dela Gothic One Regular.ttf", "1976450_Black Han Sans Regular.ttf",
  "16378366_Encode Sans SC SemiExpanded ExtraBold.ttf",
  "16378190_Fraunces 9pt SuperSoft Black.ttf",
  "16464578_Belanosima SemiBold.ttf",
  "16465010_Bricolage Grotesque 24pt ExtraBold.ttf",
  "16465466_Commissioner Black.ttf",
  "16466002_DynaPuff Medium.ttf",
  "16469878_Prompt-SemiBold.ttf",
  "Barrio-Regular.ttf", "MarkPro-Heavy.otf", "FrederickatheGreat-Regular.ttf",
  "2216050_Reenie Beanie.ttf", "STENCIL.TTF", "JOKERMAN.TTF",
  "AGENCYR.TTF", "ERASBD.TTF", "ERASDEMI.TTF",
  "FRADM.TTF", "FRAHV.TTF", "BOOKOS.TTF",
  "ARCHITECTSDAUGHTER-REGULAR.TTF", "IMFeGPrm28P.ttf", "IMFePIit28P.ttf", "IMFePIrm28P.ttf",
  "Baloo-Regular.ttf", "BALOOBHAINA-REGULAR.TTF", "FREESCPT.TTF", "ZCOOL Addict Italic 01.ttf",
  // --- remainder of assets/Fonts (added in 1.6.0; every file on disk is now listed) ---
  "16485066_Bebas Neue Regular.ttf", "2035040_Bebas Neue.ttf", "BEBAS__.ttf",
  "Arizonia-Regular.ttf",
  "AveriaSerifLibre-Italic.ttf", "AveriaSerifLibre-Light.ttf", "AveriaSerifLibre-Regular.ttf",
  "GreatVibes-Regular_0.ttf", "Lato-Light_0.ttf", "Raleway-Regular_0.ttf",
  "Montserrat-BlackItalic.ttf", "RUBIK-EXTRABOLD.TTF", "Orbitron-Light.ttf",
  "TiltWarp-Regular.ttf", "roguehero3d.ttf", "MPLUS1p-Regular.ttf",
  "RobotoCondensed-Bold_0.ttf", "RobotoCondensed-BoldItalic_0.ttf",
  "RobotoCondensed-Italic_0.ttf", "RobotoCondensed-Light_0.ttf",
  "RobotoCondensed-LightItalic_0.ttf", "RobotoCondensed-Regular_0.ttf",
  "Lohit Telugu Regular.ttf", "Nirmala.ttf", "monbaiti.ttf", "mvboli.ttf",
  "bahnschrift.ttf", "segoepr.ttf", "seguibl.ttf",
  "calibri.ttf", "calibrii.ttf", "calibril.ttf", "arial.ttf", "ARIALN.TTF", "ARIALUNI.TTF",
];

const WEIGHT_TOKENS = [
  ["Thin", 100], ["ExtraLight", 200], ["UltraLight", 200], ["Light", 300],
  ["Regular", 400], ["Normal", 400], ["Medium", 500], ["SemiBold", 600], ["DemiBold", 600],
  ["Bold", 700], ["ExtraBold", 800], ["UltraBold", 800], ["Black", 900], ["Heavy", 900],
  ["Fat", 900],
];
const STYLE_TOKENS = ["Italic", "Oblique", "Slant"];

function parseFontFilename(file) {
  const base = file.replace(/\.(ttf|otf)$/i, "");
  // Filmora ships de-duplicated copies as "Name-Weight_0.ttf" / "_1" — the numeric
  // suffix is a copy counter, not part of the family name.
  const cleaned = base.replace(/^\d+_+/, "").replace(/_\d+$/, "");
  let family = cleaned;
  let weight = 400;
  let style = "normal";
  const tokens = cleaned.split(/[\s_-]+/).filter(Boolean);
  while (tokens.length > 1) {
    const last = tokens[tokens.length - 1];
    const wt = WEIGHT_TOKENS.find(([w]) => last.toLowerCase() === w.toLowerCase());
    if (wt) { weight = wt[1]; tokens.pop(); continue; }
    if (STYLE_TOKENS.some((s) => last.toLowerCase() === s.toLowerCase())) {
      style = last.toLowerCase(); tokens.pop(); continue;
    }
    break;
  }
  family = tokens.join(" ");
  if (family.endsWith(" Regular")) family = family.slice(0, -9);
  if (!family) family = base;
  return { family, weight, style, label: cleaned };
}

let _fonts = null;
export function fonts() {
  if (_fonts) return _fonts;
  _fonts = FONT_FILES.map((file) => {
    const { family, weight, style, label } = parseFontFilename(file);
    const url = BASE + "Fonts/" + encodeURIComponent(file);
    const id = family.toLowerCase().replace(/[^a-z0-9]+/g, "-") + "-" + weight + (style !== "normal" ? "i" : "");
    return { id, family, weight, style, file, url, label };
  });
  const seen = new Set();
  _fonts = _fonts.filter((f) => (seen.has(f.id) ? false : seen.add(f.id)));
  return _fonts;
}

let _fontsInjected = false;
export function injectFontFace(doc = (typeof document !== "undefined" ? document : null)) {
  if (_fontsInjected || !doc) return;
  _fontsInjected = true;
  const css = fonts()
    .map((f) =>
      `@font-face{font-family:"${f.family}";font-style:${f.style};font-weight:${f.weight};font-display:swap;src:url("${f.url}") format("${f.file.toLowerCase().endsWith(".otf") ? "opentype" : "truetype"}")}`
    )
    .join("");
  let style = doc.getElementById("assets-bridge-fonts");
  if (!style) {
    style = doc.createElement("style");
    style.id = "assets-bridge-fonts";
    doc.head.appendChild(style);
  }
  style.textContent = css;
}

export function featuredFontFamilies() {
  const curated = [
    "Bebas Neue", "Bebas Neue Bold", "Bebas Neue Light",
    "Montserrat", "Montserrat Black", "Montserrat Bold", "Montserrat ExtraBold", "Montserrat Light",
    "Roboto", "Roboto Bold", "Roboto Condensed",
    "Open Sans", "Open Sans Bold", "Open Sans Semibold", "Open Sans ExtraBold",
    "Poppins", "Poppins Bold",
    "Oswald", "Oswald Light", "Oswald SemiBold",
    "Raleway", "Raleway Bold", "Raleway ExtraBold",
    "Anton", "Bangers", "Pacifico", "Caveat", "Permanent Marker", "Press Start 2P",
    "Playfair Display", "DM Serif Display", "Cinzel",
    "Teko", "Outfit", "Satisfy", "Cookie", "Sacramento", "Sigmar One",
    "Barlow", "Barlow Condensed", "Lato", "Lato Bold", "Quicksand",
  ];
  const all = fonts();
  return curated.map((name) => all.find((f) => f.family.toLowerCase() === name.toLowerCase())).filter(Boolean);
}

/* ---------------- caption animations ----------------------------------------------- */
const ANIM_TO_KEY = {
  "fade": "fade",
  "cinema style": "cinema", "cinema-style": "cinema", "cinemastyle": "cinema",
  "wavy style": "wavy", "wavy-style": "wavy", "wavystyle": "wavy",
  "type writer": "typewriter", "type-writer": "typewriter", "typewriter": "typewriter",
  "doomo": "pop", "doomo design": "pop", "domoodesign": "pop",
  "string blur": "blur",
  "richtick": "pop", "rich tick": "pop",
  "random": "pop", "radom": "pop", "random 2": "fade",
  "evaporate": "fade",
  "no animation": null,
  "boom": "pop", "boom!": "pop",
  "wham": "pop", "wham!": "pop",
  "drop": "drop", "drop_": "drop",
  "pixelate": "pop",
  "pinwheel": "spin",
  "erase": "fade",
  "crosszoom": "zoom",
  "doorway": "fade",
  "roll clockwise": "roll", "roll_clockwise": "roll",
  "round zoom out": "zoomout", "rounde_zoom_out": "zoomout",
  "twrl": "spin",
  "linear wipe": "wipe", "linearwipe": "wipe",
  "push": "slideup",
  "skew right split": "slideup", "skew_right_split": "slideup",
  "up insert": "slideup", "up-insert": "slideup", "up_insert": "slideup",
  "down insert": "slidedown", "down-insert": "slidedown", "down_insert": "slidedown",
  "up dir insert": "slideup",
  "left dir insert": "slideleft",
  "right dir insert": "slideright",
  "down dir insert": "slidedown",
  "up roll": "roll", "down roll": "roll", "left roll": "roll", "right roll": "roll",
  "bounce": "bounce", "spin": "spin", "rotate": "spin",
  "zoom": "zoom", "zoom in": "zoom", "zoom out": "zoomout",
  "fly": "fly", "flip": "flip", "stretch": "stretch",
  "move to": "slide", "grow shrink": "pop", "photo spin": "spin",
  "tiny zoom": "zoom", "expansion": "zoom",
};

const CAPTION_DIRS = {
  base: BASE + "resources/captions/Base/",
  guid: BASE + "resources/captions/AnimationWithGUID/",
  motion: BASE + "resources/captions/Motion/",
};

const CAPTION_FILES = {
  base: [
    "No Animation.png", "Random 2.png", "cinema-style.png", "doomo.png", "radom.png",
    "richtick.png", "string-Blur.png", "type-writer.png", "wavy - style.png",
    "Evaporate 1.png",
  ],
  guid: [
    "Down Dir Insert.png", "Down Insert_An.png", "Down Roll_An.png",
    "Evaporate 1.png", "Fade.png", "Fade_An.png", "Left Roll_An.png",
    "Right Dir Insert.png", "Right Roll_An.png", "Up Dir Insert.png",
    "Up Insert_An.png", "Up-Roll.png",
    "crosszoom.png", "doorway.png", "drop.png", "erase.png",
    "left Dir Insert.png", "linear wipe.png", "pinwheel.png", "pixelate.png",
    "push.png", "roll_clockwise.png", "rounde_zoom_out.png", "skew_right_split.png",
    "twrl.png",
  ],
  motion: [
    "Boom!.png", "Bounce to zoom in 1.png", "Bounce to zoom in 2.png",
    "Bounce to zoom out 1.png", "Clockwise rotate to zoom in 1.png",
    "Clockwise rotate to zoom in 2.png", "Clockwise rotate.png",
    "Counter clockwise rotate.png", "Down Up 1.png", "Down Up 2.png",
    "Drop_An.png", "Expansion.png", "Fade Slide 1.png", "Fade Slide 2.png",
    "Fade Slide 3.png", "Fade Slide 4.png", "Fade Zoom In.png", "Fade Zoom Out.png",
    "Fade.png", "Flip Down1.png", "Flip Down2.png", "Flip Up1.png", "Flip Up2.png",
    "Fly in and Fade out.png", "Fly in and Fly out.png", "Fly to zoom in.png",
    "Grow Shrink.png", "Move to bottom.png", "Move to left.png",
    "Move to lower left.png", "Move to lower right.png", "Move to right.png",
    "Move to top.png", "Move to upper left.png", "Move to upper right and zoom in.png",
    "Move to upper right.png", "No Motion.png", "Photo Spin 3.png", "Photo Spin 4.png",
    "Rotate to zoom in 1.png", "Rotate to zoom in 2.png", "Spin 1.png", "Spin 2.png",
    "Spin 3.png", "Spin 4.png", "Stretch in and zoom in 1.png", "Stretch in and zoom in 2.png",
    "Stretch in and zoom in.png", "Stretch to left.png", "Stretch to right.png",
    "Tiny zoom.png", "To the Left 1.png", "To the Left 2.png", "To the Right 1.png",
    "To the Right 2.png", "Up Down 1.png", "Up Down 2.png", "Wham!.png",
    "Zoom In.png", "Zoom Out.png", "Zoom in 1.png", "Zoom in 2.png", "Zoom in 3.png",
    "Zoom in and out.png", "Zoom in to the bottom.png", "Zoom in to the left.png",
    "Zoom in to the right.png", "Zoom in to the top.png", "Zoom out 1.png",
    "Zoom out 2.png", "Zoom out 3.png", "Zoom out to the right.png",
  ],
};

function keyOfCaption(label) {
  const norm = label.toLowerCase().replace(/[_-]+/g, " ").replace(/\s+/g, " ").trim();
  if (ANIM_TO_KEY[norm] !== undefined) return ANIM_TO_KEY[norm];
  for (const k of Object.keys(ANIM_TO_KEY)) {
    if (k === "no animation") continue;
    if (norm.includes(k)) return ANIM_TO_KEY[k];
  }
  return "fade";
}

let _capAnims = null;
export function captionAnimations() {
  if (_capAnims) return _capAnims;
  const out = [];
  for (const [kind, list] of Object.entries(CAPTION_FILES)) {
    list.forEach((file, i) => {
      const label = file.replace(/\.(png|xml)$/i, "").trim();
      out.push({
        id: kind + ":" + i,
        kind,
        label,
        thumb: CAPTION_DIRS[kind] + encodeURIComponent(file),
        key: keyOfCaption(label),
        file,
      });
    });
  }
  _capAnims = out;
  return _capAnims;
}

/* ---------------- Filmora-derived theme presets -----------------------------------
 * Values are MEASURED, not guessed: every hex below was counted across
 * assets/Skin/filmora_dark.txt (2 348 literals) and filmora_light.txt (2 374).
 * Filmora builds surfaces from translucent white overlays on a near-black base —
 *   4% resting · 6% hover/track · 8% chip · 14% selected · 24% separator · 30%-black input
 * which is why it reads as "glassy" where a solid grey ladder does not.
 * See research/FILMORA-THEME-RESEARCH.md.
 */
export const THEME_PRESETS = {
  "filmora-dark": {
    label: "Filmora Dark",
    tokens: {
      // surfaces — measured
      "--bg": "#0a0d0f", // deepest (BGColorType 13) · 45 uses
      "--bg-deep": "#000000", // FTimelineModuleWidget
      "--bg-elev": "#15191c", // deep surface · 50 uses
      "--panel": "#181c1f", // panel surface · 264 uses
      "--panel-2": "#202427", // card surface
      "--panel-3": "#2e353a", // hover surface · 31 uses
      "--elevated": "#21282d", // timeline surface · 85 uses
      "--card": "#202427",
      // translucent overlays — Filmora's signature
      "--surface-1": "rgba(217, 223, 235, 0.04)",
      "--surface-2": "rgba(217, 223, 235, 0.06)",
      "--surface-3": "rgba(199, 212, 224, 0.14)",
      "--surface-chip": "rgba(154, 179, 202, 0.08)",
      "--field": "rgba(0, 0, 0, 0.30)",
      // strokes
      "--border": "#363e44", // control border · 149 uses
      "--border-soft": "#21282d",
      "--border-hover": "#4f575d",
      "--stroke-1": "rgba(202, 232, 255, 0.14)",
      "--stroke-2": "rgba(234, 247, 255, 0.06)",
      "--stroke-3": "rgba(255, 255, 255, 0.24)",
      "--scrollbar": "#363e44",
      // text ramp — 4 measured steps
      "--ink": "#f0f8fe", // primary · 394 uses
      "--ink-strong": "#f0f8fe",
      "--ink-body": "#c3cad0", // body · 286 uses
      "--ink-dim": "#c3cad0",
      "--ink-muted": "#959ca2", // muted · 125 uses
      "--ink-disabled": "#4f575d", // disabled · 96 uses
      "--muted": "#959ca2",
      "--on-accent": "#0a0d0f", // dark text on the bright cyan fill
      // accents
      "--accent": "#55e5c5", // brand cyan · 249 uses
      "--accent-soft": "rgba(85, 229, 197, 0.16)",
      "--accent-strong": "#99efdc", // accent tint · 28 uses
      "--accent-ai": "#3ddcff", // AI accent · 18 uses
      "--gen": "#45f3bf", // bright cyan · 18 uses
      "--gen-soft": "rgba(69, 243, 191, 0.14)",
      "--warn": "#ffb020",
      "--warn-soft": "rgba(255, 176, 32, 0.14)",
      "--danger": "#ff6161", // · 40 uses
      "--danger-soft": "rgba(255, 97, 97, 0.14)",
      "--violet": "#a78bfa",
      // clip identities
      "--clip-video": "#3d6fd4",
      "--clip-audio": "#2f9e6b",
      "--clip-text": "#c9a227",
      "--clip-ai": "#8b5cf6",
      "--clip-gen": "#0d9488",
      // chrome
      "--titlebar-grad": "linear-gradient(180deg, #14191e, #0b1318)",
    },
  },
  "filmora-light": {
    label: "Filmora Light",
    tokens: {
      "--bg": "#f5f8fa", // app bg · 158 uses
      "--bg-deep": "#eaeef0",
      "--bg-elev": "#ffffff",
      "--panel": "#ffffff", // panel · 326 uses
      "--panel-2": "#f1f5f7", // hover · 31 uses
      "--panel-3": "#e9edf0",
      "--elevated": "#ecf0f2", // · 48 uses
      "--card": "#ffffff",
      // inverted overlays (dark ink at low alpha reads as grey on white)
      "--surface-1": "rgba(42, 52, 56, 0.04)",
      "--surface-2": "rgba(42, 52, 56, 0.06)",
      "--surface-3": "rgba(42, 52, 56, 0.14)",
      "--surface-chip": "rgba(42, 52, 56, 0.08)",
      "--field": "rgba(42, 52, 56, 0.06)",
      // strokes
      "--border": "#e9edf0", // · 124 uses
      "--border-soft": "#eaeef0",
      "--border-hover": "#b1b8bc",
      "--stroke-1": "rgba(42, 52, 56, 0.14)",
      "--stroke-2": "rgba(42, 52, 56, 0.08)",
      "--stroke-3": "rgba(42, 52, 56, 0.24)",
      "--scrollbar": "#b1b8bc",
      // text ramp — measured light values
      "--ink": "#2a3438", // primary · 392 uses
      "--ink-strong": "#2a3438",
      "--ink-body": "#646c72", // body · 296 uses
      "--ink-dim": "#646c72",
      "--ink-muted": "#8e959b", // muted · 125 uses
      "--ink-disabled": "#b1b8bc", // disabled · 96 uses
      "--muted": "#8e959b",
      "--on-accent": "#ffffff",
      // accents
      "--accent": "#25c2a4", // brand cyan (dark enough for white bg) · 249 uses
      "--accent-soft": "rgba(37, 194, 164, 0.16)",
      "--accent-strong": "#2faa92", // · 28 uses
      "--accent-ai": "#207fee", // · 21 uses
      "--gen": "#23cfae", // · 25 uses
      "--gen-soft": "rgba(35, 207, 174, 0.14)",
      "--warn": "#a66500",
      "--warn-soft": "rgba(166, 101, 0, 0.14)",
      "--danger": "#f05555", // · 40 uses
      "--danger-soft": "rgba(240, 85, 85, 0.14)",
      "--violet": "#7c5cf0",
      "--clip-video": "#3d6fd4",
      "--clip-audio": "#2f9e6b",
      "--clip-text": "#c9a227",
      "--clip-ai": "#8b5cf6",
      "--clip-gen": "#0d9488",
      "--titlebar-grad": "linear-gradient(180deg, #ffffff, #f1f5f7)",
    },
  },
};

/** Names of every token a preset can override (so we can undo them cleanly). */
const PRESET_TOKEN_NAMES = (() => {
  const names = new Set();
  for (const p of Object.values(THEME_PRESETS)) Object.keys(p.tokens).forEach((k) => names.add(k));
  return Array.from(names);
})();

export function applyThemePreset(name) {
  const preset = THEME_PRESETS[name];
  if (!preset || typeof document === "undefined") return false;
  const root = document.documentElement;
  for (const [k, v] of Object.entries(preset.tokens)) root.style.setProperty(k, v);
  root.setAttribute("data-theme-preset", name);
  return true;
}

/** Undo any inline preset overrides so the stylesheet defaults take over again. */
export function clearThemePreset() {
  if (typeof document === "undefined") return;
  const root = document.documentElement;
  PRESET_TOKEN_NAMES.forEach((k) => root.style.removeProperty(k));
  root.removeAttribute("data-theme-preset");
}

export function isThemePreset(name) {
  return Object.prototype.hasOwnProperty.call(THEME_PRESETS, name);
}

export function listThemePresets() {
  return Object.entries(THEME_PRESETS).map(([id, p]) => ({ id, label: p.label }));
}

/* ---------------- asset manifest fetchers ----------------------------------------- */
export async function shapeManifest() {
  try {
    const r = await fetch(BASE + "shapes/manifest.json");
    if (!r.ok) return { items: [] };
    return await r.json();
  } catch { return { items: [] }; }
}

export async function transitionManifest() {
  try {
    const r = await fetch(BASE + "transitions/manifest.json");
    if (!r.ok) return { items: [] };
    return await r.json();
  } catch { return { items: [] }; }
}

/* ---------------- caption textures ------------------------------------------------ */
export const CAPTION_TEXTURES = [
  "abstract1.png", "abstract2.png", "abstract4.png", "abstract5.png",
  "marble3.png", "noise1.png", "paper3.png", "paper4.png", "paper5.png",
  "plastic4.png", "plastic5.png", "tetxile5.png", "textile1.png",
  "textile3.png", "textile4.png",
];
export const CAPTION_TEXTURE_BASE = BASE + "Captions/Texttures/TexturePreset/";

/* ---------------- AI sample assets ------------------------------------------------ */
export const AI_SAMPLES = [
  { id: "color-swap", label: "Color Palette Swap", src: BASE + "AIClip/ColorPaletteSwap1.png" },
  { id: "fashion", label: "Fashion 1", src: BASE + "AIClip/Fashion1.png" },
  { id: "figurine", label: "Figurine 1", src: BASE + "AIClip/Figurine1.png" },
  { id: "nano-banana", label: "NanoBanana Palette", src: BASE + "AINanoBanana/ColorPaletteSwap1.png" },
  { id: "watermark", label: "Watermark Preview", src: BASE + "AIWatermark/PreviewWaterMark.png" },
];

/* ---------------- boot ------------------------------------------------------------ */
export function bootAssets() {
  if (typeof document !== "undefined") injectFontFace();
  fonts();
  captionAnimations();
  if (typeof window !== "undefined") {
    window.dispatchEvent(new CustomEvent("aifimora:assets-ready"));
  }
}