/* GENERATED by gen-color.cjs — do not edit by hand.
 * Filmora built-in colour presets. Every number below was read out of
 * assets/configs/ColorAnd3dLutPreset/default/<name>/Data/<name>.conf, so these
 * are the values Filmora itself applies — not approximations.
 * Re-run `node gen-color.cjs` after changing the asset dump.
 */

export const COLOR_PRESET_BANDS = ["Red","Orange","Yellow","Green","Aqua","Blue","Purple","Magenta"];

export const COLOR_PRESETS = [
  {
    "id": "color:color_Black&White",
    "title": "Black&White",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": -100,
      "saturation": -100
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Blockbuster",
    "title": "Blockbuster",
    "lutPath": "",
    "wb": {
      "temp": -38.92707443237305,
      "tint": 0
    },
    "color": {
      "exposure": 3,
      "brightness": 0,
      "contrast": 84,
      "vibrance": 11,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 52,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 100,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 51,
        "bri": 34
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 93,
        "bri": -12
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 23,
        "bri": -36
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 29,
        "bri": -46
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 39,
        "bri": -41
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": -39
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Boost_Color",
    "title": "Boost Color",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 100,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Brighten",
    "title": "Brighten",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 19,
      "brightness": 0,
      "contrast": 32,
      "vibrance": 67,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Cool",
    "title": "Cool",
    "lutPath": "",
    "wb": {
      "temp": -58.681636810302734,
      "tint": 20.448984146118164
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Cool_Max",
    "title": "Cool Max",
    "lutPath": "",
    "wb": {
      "temp": -100,
      "tint": 17.146780014038086
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Darken",
    "title": "Darken",
    "lutPath": "",
    "wb": {
      "temp": -3.9746029376983643,
      "tint": 0.16871799528598785
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 73,
      "vibrance": -40,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 16,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 46,
        "bri": 24
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 6,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": -36,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": -41,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": -33,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": -31,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": -57,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Elegant",
    "title": "Elegant",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": -29.629623413085938
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": -19,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": -30,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Epic",
    "title": "Epic",
    "lutPath": "",
    "wb": {
      "temp": 48.505828857421875,
      "tint": 13.728677749633789
    },
    "color": {
      "exposure": 18,
      "brightness": 0,
      "contrast": 100,
      "vibrance": 48,
      "saturation": 17
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": -10,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": -7,
        "sat": -3,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 40,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 43,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Fantasy",
    "title": "Fantasy",
    "lutPath": "",
    "wb": {
      "temp": -40.210289001464844,
      "tint": 7.029076099395752
    },
    "color": {
      "exposure": 40,
      "brightness": -19,
      "contrast": 48,
      "vibrance": 57,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": -19,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Far_East",
    "title": "Far East",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": -23
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Film_Stock",
    "title": "Film Stock",
    "lutPath": "",
    "wb": {
      "temp": -6.549993991851807,
      "tint": 19.652362823486328
    },
    "color": {
      "exposure": 18,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 82,
      "saturation": 39
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": -10,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": -3,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 40,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 43,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Jungle",
    "title": "Jungle",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 10,
      "contrast": 20,
      "vibrance": 18,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": -15,
      "size": 100,
      "feather": 75,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Lomo",
    "title": "Lomo",
    "lutPath": "",
    "wb": {
      "temp": 69.01529693603516,
      "tint": 3.451267957687378
    },
    "color": {
      "exposure": 38,
      "brightness": 5,
      "contrast": -3,
      "vibrance": 48,
      "saturation": -20
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 9,
        "sat": 0,
        "bri": 15
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": -40,
      "size": 100,
      "feather": 57,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Old_Film",
    "title": "Old Film",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": -100
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": -50,
        "bri": -57
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 52,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": -71,
        "bri": -100
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": -100,
        "bri": -55
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": -100,
        "bri": -24
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": -100,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": -100,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": -100,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Polaroid",
    "title": "Polaroid",
    "lutPath": "",
    "wb": {
      "temp": -0.4629630148410797,
      "tint": -0.3428860008716583
    },
    "color": {
      "exposure": -7,
      "brightness": 0,
      "contrast": 52,
      "vibrance": 14,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 3,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": -9,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": -41,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 7,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": -4,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": -16,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": -38,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_TV",
    "title": "TV",
    "lutPath": "",
    "wb": {
      "temp": 28.583972930908203,
      "tint": 0.003198999911546707
    },
    "color": {
      "exposure": 11,
      "brightness": -3,
      "contrast": 9,
      "vibrance": 7,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 9,
        "sat": 0,
        "bri": 15
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Vignette_10",
    "title": "Vignette 10",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": -80,
      "size": 80,
      "feather": 70,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Vignette_2",
    "title": "Vignette 2",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": -80,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Vignette_3",
    "title": "Vignette 3",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": -100,
      "size": 100,
      "feather": 84,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Vignette_4",
    "title": "Vignette 4",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 15,
      "size": 100,
      "feather": 60,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Vignette_5",
    "title": "Vignette 5",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 9,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Vignette_6",
    "title": "Vignette 6",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": -100,
      "size": 100,
      "feather": 100,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Vignette_7",
    "title": "Vignette 7",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 100,
      "size": 100,
      "feather": 100,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Vignette_8",
    "title": "Vignette 8",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 60,
      "size": 100,
      "feather": 30,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Vignette_9",
    "title": "Vignette 9",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": -69,
      "size": 89,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Vignette_Classic",
    "title": "Vignette Classic",
    "lutPath": "",
    "wb": {
      "temp": 0,
      "tint": 0
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": -50,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Warm",
    "title": "Warm",
    "lutPath": "",
    "wb": {
      "temp": 42.5153923034668,
      "tint": 5.480485916137695
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  },
  {
    "id": "color:color_Warm_Max",
    "title": "Warm Max",
    "lutPath": "",
    "wb": {
      "temp": 100,
      "tint": -0.10982900112867355
    },
    "color": {
      "exposure": 0,
      "brightness": 0,
      "contrast": 0,
      "vibrance": 0,
      "saturation": 0
    },
    "light": {
      "highlight": 0,
      "shadow": 0,
      "white": 0,
      "black": 0
    },
    "hsl": {
      "Red": {
        "min": 338,
        "max": 25,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Orange": {
        "min": 8,
        "max": 45,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Yellow": {
        "min": 35,
        "max": 100,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Green": {
        "min": 67.5,
        "max": 171,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Aqua": {
        "min": 168,
        "max": 218,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Blue": {
        "min": 195,
        "max": 250,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Purple": {
        "min": 258,
        "max": 280,
        "hue": 0,
        "sat": 0,
        "bri": 0
      },
      "Magenta": {
        "min": 281,
        "max": 330,
        "hue": 0,
        "sat": 0,
        "bri": 0
      }
    },
    "vignette": {
      "amount": 0,
      "size": 100,
      "feather": 50,
      "roundness": 0
    }
  }
];

const BY_ID = new Map(COLOR_PRESETS.map((p) => [p.id, p]));
export function colorPresets() { return COLOR_PRESETS; }
export function colorPresetById(id) { return BY_ID.get(id) || null; }
export function colorPresetByTitle(t) {
  const q = String(t || "").toLowerCase();
  return COLOR_PRESETS.find((p) => p.title.toLowerCase() === q) || null;
}
