/* lut-panel.js — the Filmora LUT browser.
 *
 * 25 genuine 32³ .CUBE files ship in assets/configs/ColorAnd3dLutPreset/CubeLUTFiles.
 * This panel gives them a real home: a searchable grid of thumbnails generated by
 * pushing a reference colour chart through each LUT, so you can see what a look
 * does before you commit it.
 *
 * Selection reuses the existing FX dropdown wiring (set value + dispatch change)
 * rather than reaching into effects.js internals.
 */
import { toast } from "./media.js";
import {
  LUT_NAMES,
  loadLut,
  getCachedLut,
  lutThumbnail,
  referenceThumbnail,
  LUT_PREFIX,
  preloadLuts,
} from "./lut-engine.js";

let built = false;

function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) => (
    { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]
  ));
}

function applyLutValue(value, label) {
  const sel = document.getElementById("fxLut");
  if (!sel) return;
  sel.value = value;
  sel.dispatchEvent(new Event("change"));
  window.__aifimoraPlayer?.render();
  if (label) toast("LUT · " + label, "ok");
}

/** Add the Filmora LUTs as an <optgroup> in the plain FX dropdown.
 *  Guarded by a data flag, but effects.js rebuilds the dropdown wholesale on a
 *  settings change, so the flag has to be cleared whenever innerHTML is reset —
 *  effects.js calls this on every rebuild, which covers that. */
export function populateFilmoraLutOptions(sel) {
  if (!sel) return;
  // Presence check, not a sticky flag: effects.js resets innerHTML on a settings
  // change, which would leave a flag lying about the group still being there.
  const has = Array.from(sel.querySelectorAll("optgroup")).some(
    (g) => g.dataset.filmoraLuts === "1"
  );
  if (has) return;
  const group = document.createElement("optgroup");
  group.dataset.filmoraLuts = "1";
  group.label = "Filmora .CUBE";
  LUT_NAMES.forEach((n) => {
    const o = document.createElement("option");
    o.value = LUT_PREFIX + n;
    o.textContent = n;
    group.appendChild(o);
  });
  sel.appendChild(group);
}

function tile(name) {
  const cached = getCachedLut(name);
  const thumb = cached ? lutThumbnail(cached, 112, 63) : referenceThumbnail(112, 63);
  const ready = !!cached;
  return `<button type="button" class="lut-tile${ready ? "" : " pending"}" data-lut="${esc(name)}"
      role="option" aria-selected="false" title="${esc(name)}">
      <span class="lut-thumb" style="background-image:url('${thumb}')"></span>
      <span class="lut-name">${esc(name)}</span>
    </button>`;
}

function renderGrid(filter = "") {
  const grid = document.getElementById("lutGrid");
  if (!grid) return;
  const q = filter.trim().toLowerCase();
  const names = q ? LUT_NAMES.filter((n) => n.toLowerCase().includes(q)) : LUT_NAMES;
  grid.innerHTML = names.length
    ? names.map(tile).join("")
    : `<p class="empty-hint">No LUT matches “${esc(filter)}”.</p>`;
  const hint = document.getElementById("lutCountHint");
  if (hint) hint.textContent = `${names.length} of ${LUT_NAMES.length} LUTs`;
}

function syncActive() {
  const sel = document.getElementById("fxLut");
  const cur = sel?.value || "none";
  document.querySelectorAll("#lutGrid .lut-tile").forEach((b) => {
    const on = LUT_PREFIX + b.dataset.lut === cur;
    b.classList.toggle("active", on);
    b.setAttribute("aria-selected", on ? "true" : "false");
  });
}

export function initLutBrowser() {
  const grid = document.getElementById("lutGrid");
  const search = document.getElementById("lutSearch");
  const sel = document.getElementById("fxLut");
  if (!grid) return;

  populateFilmoraLutOptions(sel);
  renderGrid();
  built = true;

  search?.addEventListener("input", () => renderGrid(search.value));

  grid.addEventListener("click", (e) => {
    const btn = e.target.closest(".lut-tile");
    if (!btn) return;
    const name = btn.dataset.lut;
    applyLutValue(LUT_PREFIX + name, name);
    syncActive();
    // make sure the tile is graded, not the neutral reference chart
    loadLut(name)
      .then(() => { renderGrid(search?.value || ""); syncActive(); })
      .catch(() => {});
  });

  sel?.addEventListener("change", syncActive);
  window.addEventListener("aifimora:clip-selected", syncActive);

  // Grade every thumbnail in the background. Tiles repaint as each .CUBE lands.
  preloadLuts(() => {
    if (!built) return;
    renderGrid(search?.value || "");
    syncActive();
  });
}
