/* GENERATED by gen-panzoom.cjs — do not edit by hand.
 * Filmora Pan & Zoom presets, read from assets/configs/PanZoom/*.conf.
 *
 * Each preset has four keyframed tracks — crop X, Y, Width, Height — as
 * normalised 0..1 fractions of the frame, sampled over the clip duration.
 * ZoomOriginal is 0,0,1,1; ZoomIn is 1 -> 0.5 on W/H with X/Y 0 -> 0.25 to
 * keep the crop centred. These are Filmora's own curves.
 *
 * Re-run `node gen-panzoom.cjs` after changing the asset dump.
 */

export const PANZOOM_PRESETS = [
  {
    "id": "panzoom:zoom-to-bottom-right",
    "title": "Zoom to bottom right",
    "config": "ZoomToBottomRight.conf",
    "category": "Default",
    "tracks": [
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 1,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 1,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      }
    ]
  },
  {
    "id": "panzoom:zoom-in",
    "title": "Zoom in",
    "config": "ZoomIn.conf",
    "category": "Default",
    "tracks": [
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.25,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.25,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 1,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 1,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      }
    ]
  },
  {
    "id": "panzoom:zoom-out",
    "title": "Zoom out",
    "config": "ZoomOut.conf",
    "category": "Default",
    "tracks": [
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.25,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.25,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.5,
            "interp": 1
          },
          {
            "t": 1,
            "v": 1,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.5,
            "interp": 1
          },
          {
            "t": 1,
            "v": 1,
            "interp": 1
          }
        ]
      }
    ]
  },
  {
    "id": "panzoom:pan-right",
    "title": "Pan Right",
    "config": "PanRight.conf",
    "category": "Default",
    "tracks": [
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.25,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.25,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.5,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.5,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      }
    ]
  },
  {
    "id": "panzoom:pan-left",
    "title": "Pan Left",
    "config": "PanLeft.conf",
    "category": "Default",
    "tracks": [
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.5,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.25,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.25,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.5,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0.5,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0.5,
            "interp": 1
          }
        ]
      }
    ]
  },
  {
    "id": "panzoom:zoom-original",
    "title": "Zoom Original",
    "config": "ZoomOriginal.conf",
    "category": "Default",
    "tracks": [
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 0,
            "interp": 1
          },
          {
            "t": 1,
            "v": 0,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 1,
            "interp": 1
          },
          {
            "t": 1,
            "v": 1,
            "interp": 1
          }
        ]
      },
      {
        "min": -100,
        "max": 100,
        "base": 1,
        "keys": [
          {
            "t": 0,
            "v": 1,
            "interp": 1
          },
          {
            "t": 1,
            "v": 1,
            "interp": 1
          }
        ]
      }
    ]
  }
];

const BY_ID = new Map(PANZOOM_PRESETS.map((p) => [p.id, p]));
export function panZoomPresets() { return PANZOOM_PRESETS; }
export function panZoomById(id) { return BY_ID.get(id) || null; }
