/* One-off generator: scans assets/ and bakes directory listings into js/filmora-library.js.
 * Browsers cannot list directories, so every URL has to be enumerated at build time. */
const fs = require("fs");
const A = "assets/";

const rd = (p) => { try { return fs.readdirSync(p, { withFileTypes: true }); } catch { return []; } };
const enc = (s) => encodeURIComponent(s);

/* ---- 1. LUTs ---- */
const luts = rd(A + "configs/ColorAnd3dLutPreset/CubeLUTFiles")
  .filter((d) => d.isFile() && /\.CUBE$/i.test(d.name))
  .map((d) => d.name.replace(/\.CUBE$/i, ""))
  .sort();

/* ---- 2. audio effects (read each description.json for real params) ---- */
const AUDIO_DIR = A + "resources/audio_effect/";
const audio = [];
for (const d of rd(AUDIO_DIR)) {
  if (!d.isDirectory()) continue;
  const dir = AUDIO_DIR + d.name + "/";
  let meta = null;
  try { meta = JSON.parse(fs.readFileSync(dir + "description.json", "utf8")); } catch { continue; }
  const params = (meta.params || []).map((p) => ({
    n: p.name, min: p.min_value, max: p.max_value, def: p.default_value,
  }));
  audio.push({ id: d.name, label: meta.display_name || d.name, uniq: meta.unique_name || "", params });
}
audio.sort((a, b) => a.id.localeCompare(b.id));

/* ---- 3. text styles (PNG thumbnails) ---- */
const TS = A + "configs/TextStyle/";
const textStyles = rd(TS)
  .filter((d) => d.isFile() && /\.png$/i.test(d.name))
  .map((d) => ({ name: d.name.replace(/\.png$/i, ""), thumb: TS + enc(d.name) }))
  .sort((a, b) => a.name.localeCompare(b.name));

/* ---- 4. text art ---- */
const TA = A + "configs/TextArt/";
const textArt = rd(TA).filter((d) => d.isDirectory()).map((d) => d.name).sort();

/* ---- 5. motion presets ---- */
const MO = A + "configs/Motion/";
const motion = rd(MO).filter((d) => d.isFile() && /\.conf$/i.test(d.name))
  .map((d) => d.name.replace(/\.conf$/i, "")).sort();

/* ---- 6. animation presets (in / out / combo) ---- */
const ANIM_DIR = A + "configs/AnimationNew/";
const anims = [];
for (const d of rd(ANIM_DIR)) {
  if (!d.isDirectory() || !/^\{/.test(d.name)) continue;
  const dir = ANIM_DIR + d.name + "/";
  let info = null;
  try { info = JSON.parse(fs.readFileSync(dir + "info.json", "utf8")); } catch { continue; }
  if (!info || !info.title) continue;
  anims.push({ id: d.name, title: info.title, cat: info.category || "" });
}
anims.sort((a, b) => (a.cat + a.title).localeCompare(b.cat + b.title));

/* ---- 7. masks ---- */
const MP = A + "configs/MaskPreset/";
const masks = [];
for (const grp of rd(MP)) {
  if (!grp.isDirectory()) continue;
  for (const d of rd(MP + grp.name)) {
    if (!d.isDirectory()) continue;
    masks.push({ id: d.name, name: d.name.replace(/^60_mask_/, "").replace(/_/g, " ") });
  }
}
masks.sort((a, b) => a.id.localeCompare(b.id));

/* ---- 8. filter presets (Filmora built-in looks) ---- */
const FD = A + "resources/wfx_effect/nle_default/";
const filters = rd(FD).filter((d) => d.isDirectory()).map((d) => d.name).sort();

/* ---- 9. transitions with real thumbnails + preview videos ---- */
const TD = A + "configs/Transition/Default Transitions/";
const trans = [];
for (const d of rd(TD)) {
  if (!d.isDirectory()) continue;
  const dir = TD + d.name + "/";
  const files = rd(dir).map((f) => f.name);
  if (!files.includes("thumbnail.png")) continue;
  trans.push({
    id: d.name.replace(/^\d+_/, "").toLowerCase(),
    name: d.name.replace(/^\d+_/, "").replace(/_/g, " "),
    thumb: dir + "thumbnail.png",
    video: files.includes("previewVideo.mp4") ? dir + "previewVideo.mp4" : null,
  });
}

const pad = (n) => String(n).padStart(3);
/* Asset paths such as `resources/audio_effect/<star>/` contain a comment-closing
 * sequence when written with a glob star. Escape it before emitting the header. */
const out = `/* filmora-library.js — GENERATED by gen-library.cjs. Do not hand-edit.
 *
 * Enumerates the preset libraries that ship inside \`assets/\` (a real Filmora 14
 * install). A browser cannot list a directory, so every URL is baked here at
 * build time. Re-run \`node gen-library.cjs\` after adding or removing assets.
 *
 *   LUTs          ${pad(luts.length)}  configs/ColorAnd3dLutPreset/CubeLUTFiles   real 32³ .CUBE files
 *   Audio FX      ${pad(audio.length)}  resources/audio_effect/<name>/description.json   with real param ranges
 *   Animations    ${pad(anims.length)}  configs/AnimationNew/<uuid>/info.json           in / out / combo
 *   Filters       ${pad(filters.length)}  resources/wfx_effect/nle_default          Filmora built-in looks
 *   Text art      ${pad(textArt.length)}  configs/TextArt
 *   Motion        ${pad(motion.length)}  configs/Motion
 *   Text styles   ${pad(textStyles.length)}  configs/TextStyle                          with PNG thumbnails
 *   Masks         ${pad(masks.length)}  configs/MaskPreset
 *   Transitions   ${pad(trans.length)}  configs/Transition                         thumbnail + preview video
 */

export const LUT_NAMES = ${JSON.stringify(luts, null, 2)};
export const LUT_BASE = "assets/configs/ColorAnd3dLutPreset/CubeLUTFiles/";
export const LUT_EXT = ".CUBE";

export const AUDIO_EFFECTS = ${JSON.stringify(audio)};

export const ANIMATION_PRESETS = ${JSON.stringify(anims)};

export const FILTER_PRESETS = ${JSON.stringify(filters, null, 2)};

export const TEXT_ART_PRESETS = ${JSON.stringify(textArt, null, 2)};

export const MOTION_PRESETS = ${JSON.stringify(motion, null, 2)};

export const TEXT_STYLES = ${JSON.stringify(textStyles)};

export const MASK_PRESETS = ${JSON.stringify(masks)};

export const TRANSITION_PRESETS = ${JSON.stringify(trans, null, 2)};
`;
fs.writeFileSync("js/filmora-library.js", out);
console.log("wrote js/filmora-library.js  " + (out.length / 1024).toFixed(1) + " KB");
console.log({
  luts: luts.length, audio: audio.length, anims: anims.length, filters: filters.length,
  textArt: textArt.length, motion: motion.length, textStyles: textStyles.length,
  masks: masks.length, trans: trans.length,
});
