/* Generates js/color-presets.js from Filmora's own colour presets.
 *
 * Source: assets/configs/ColorAnd3dLutPreset/default/<id>_color_<Name>/Data/<Name>.conf
 * Each .conf is JSON whose "ColorAdjust" value is itself JSON holding a paramList of
 * { name, fxParam:{ unValue } } — i.e. the ACTUAL grading numbers Filmora applies,
 * not a thumbnail or a guess. Canonical display names come from resinfo.json.
 *
 * Run: node gen-color.cjs
 */
const fs = require("fs");
const path = require("path");

const ROOT = "assets/configs/ColorAnd3dLutPreset/default";
const OUT = "js/color-presets.js";

const BANDS = ["Red", "Orange", "Yellow", "Green", "Aqua", "Blue", "Purple", "Magenta"];

function num(v, def = 0) {
  const n = Number(v);
  return Number.isFinite(n) ? n : def;
}

function parseConf(file) {
  let raw;
  try { raw = JSON.parse(fs.readFileSync(file, "utf8")); } catch { return null; }
  const flat = {};
  for (const key of Object.keys(raw)) {
    let v = raw[key];
    if (typeof v === "string") { try { v = JSON.parse(v); } catch { continue; } }
    if (v && Array.isArray(v.paramList)) {
      for (const p of v.paramList) {
        if (p && p.name && p.fxParam) flat[p.name] = p.fxParam.unValue;
      }
    }
  }
  return flat;
}

function titleFor(dir, dirName) {
  const ri = path.join(dir, "resinfo.json");
  if (fs.existsSync(ri)) {
    try {
      const j = JSON.parse(fs.readFileSync(ri, "utf8"));
      if (j.titles && j.titles.en) return String(j.titles.en);
    } catch { /* fall through to the folder name */ }
  }
  return dirName.replace(/^\d+_color_/, "").replace(/_/g, " ");
}

const presets = [];
for (const dirName of fs.readdirSync(ROOT).sort()) {
  const dir = path.join(ROOT, dirName);
  const dataDir = path.join(dir, "Data");
  if (!fs.existsSync(dataDir)) continue;
  const confFile = fs.readdirSync(dataDir).find(f => f.toLowerCase().endsWith(".conf"));
  if (!confFile) continue;
  const p = parseConf(path.join(dataDir, confFile));
  if (!p) continue;

  const hsl = {};
  BANDS.forEach((b) => {
    hsl[b] = {
      min: num(p[b + "_degreeMinVal"]),
      max: num(p[b + "_degreeMaxVal"]),
      hue: num(p[b + "_hueVal"]),
      sat: num(p[b + "_satVal"]),
      bri: num(p[b + "_brightnessVal"]),
    };
  });

  presets.push({
    id: "color:" + dirName.replace(/^\d+_/, ""),
    title: titleFor(dir, dirName),
    lutPath: typeof p.lut3dPath === "string" ? p.lut3dPath : "",
    wb: num(p.bEnableWB, 1) ? { temp: num(p.u_temperature), tint: num(p.u_tint) } : null,
    color: num(p.bEnableColor, 1) ? {
      exposure: num(p.u_exposure),
      brightness: num(p.u_brightness),
      contrast: num(p.u_contrast),
      vibrance: num(p.u_vibrance),
      saturation: num(p.u_saturation),
    } : null,
    light: num(p.bEnableLight, 1) ? {
      highlight: num(p.u_highLight),
      shadow: num(p.u_shadow),
      white: num(p.u_whiteLevel),
      black: num(p.u_blackLevel),
    } : null,
    hsl: num(p.bEnableHSL, 1) || num(p.bEnableNewHSL, 0) ? hsl : null,
    vignette: num(p.bEnableVignette, 0) ? {
      amount: num(p.amount),
      size: num(p.size),
      feather: num(p.feather),
      roundness: num(p.roundness),
    } : null,
  });
}

if (!presets.length) {
  console.error("no presets parsed — check " + ROOT);
  process.exit(1);
}

const body =
  "/* GENERATED by gen-color.cjs — do not edit by hand.\n" +
  " * Filmora built-in colour presets. Every number below was read out of\n" +
  " * assets/configs/ColorAnd3dLutPreset/default/<name>/Data/<name>.conf, so these\n" +
  " * are the values Filmora itself applies — not approximations.\n" +
  " * Re-run `node gen-color.cjs` after changing the asset dump.\n" +
  " */\n\n" +
  "export const COLOR_PRESET_BANDS = " + JSON.stringify(BANDS) + ";\n\n" +
  "export const COLOR_PRESETS = " + JSON.stringify(presets, null, 2) + ";\n\n" +
  "const BY_ID = new Map(COLOR_PRESETS.map((p) => [p.id, p]));\n" +
  "export function colorPresets() { return COLOR_PRESETS; }\n" +
  "export function colorPresetById(id) { return BY_ID.get(id) || null; }\n" +
  "export function colorPresetByTitle(t) {\n" +
  "  const q = String(t || \"\").toLowerCase();\n" +
  "  return COLOR_PRESETS.find((p) => p.title.toLowerCase() === q) || null;\n" +
  "}\n";

fs.writeFileSync(OUT, body, "utf8");
console.log("wrote " + OUT + "  " + (body.length / 1024).toFixed(1) + " KB");
console.log("presets: " + presets.length);
console.log(presets.map(p => p.title).join(" | "));
const withVig = presets.filter(p => p.vignette).length;
console.log("with vignette: " + withVig + " · with HSL: " + presets.filter(p => p.hsl).length);
