/* Generates js/panzoom-presets.js from Filmora's Pan & Zoom presets.
 *
 * Source: assets/configs/PanZoom/<Name>.conf  (titles: default_setting.json)
 *
 * The .conf is JSON-with-a-trailing-comma (strict JSON.parse rejects it). Its
 * "PanZoom" string holds FOUR tracks separated by PANZOOMKEYFRAMESEPARATOR:
 *
 *   track0 = crop X      track1 = crop Y
 *   track2 = crop Width  track3 = crop Height
 *
 * all as NORMALISED 0..1 fractions of the frame, keyframed from _time 0 to
 * 10000000. Proof that this is the model: ZoomOriginal is 0,0,1,1 (the full
 * frame) and ZoomIn shrinks W/H 1 -> 0.5 while moving X/Y 0 -> 0.25, i.e. it
 * keeps the crop centred as it zooms — exactly correct Ken Burns maths.
 *
 * Run: node gen-panzoom.cjs
 */
const fs = require("fs");
const path = require("path");

const DIR = "assets/configs/PanZoom";
const OUT = "js/panzoom-presets.js";
const TIME_MAX = 10000000; // keyframe time is normalised to this, not seconds

function readConf(file) {
  // strip the trailing comma that makes these invalid strict JSON
  const raw = fs.readFileSync(file, "utf8").replace(/,(\s*[}\]])/g, "$1");
  return JSON.parse(raw);
}

const index = JSON.parse(fs.readFileSync(path.join(DIR, "default_setting.json"), "utf8"));
const presets = [];

for (const entry of index) {
  const file = path.join(DIR, String(entry.config || "").replace(/^\//, ""));
  if (!fs.existsSync(file)) { console.warn("missing " + file); continue; }

  let obj;
  try { obj = readConf(file); }
  catch (e) { console.warn("unparseable " + file + ": " + e.message); continue; }

  const tracks = String(obj.PanZoom || "")
    .split("PANZOOMKEYFRAMESEPARATOR")
    .map((t) => { try { return JSON.parse(t); } catch { return null; } })
    .filter(Boolean);

  if (tracks.length !== 4) { console.warn("expected 4 tracks in " + file + ", got " + tracks.length); continue; }

  const norm = tracks.map((tr) => ({
    min: tr._minVal,
    max: tr._maxVal,
    base: tr._baseRatio,
    keys: (tr.keyframeSets || []).map((k) => ({
      t: Math.min(1, Math.max(0, k._time / TIME_MAX)),
      v: k._value,
      interp: k.Interpolation,
    })),
  }));

  presets.push({
    id: "panzoom:" + String(entry.title).toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    title: entry.title,
    config: path.basename(file),
    category: entry.category || "Default",
    // [x, y, w, h] tracks in that order
    tracks: norm,
  });
}

if (!presets.length) { console.error("no presets parsed"); process.exit(1); }

const body =
  "/* GENERATED by gen-panzoom.cjs — do not edit by hand.\n" +
  " * Filmora Pan & Zoom presets, read from assets/configs/PanZoom/*.conf.\n" +
  " *\n" +
  " * Each preset has four keyframed tracks — crop X, Y, Width, Height — as\n" +
  " * normalised 0..1 fractions of the frame, sampled over the clip duration.\n" +
  " * ZoomOriginal is 0,0,1,1; ZoomIn is 1 -> 0.5 on W/H with X/Y 0 -> 0.25 to\n" +
  " * keep the crop centred. These are Filmora's own curves.\n" +
  " *\n" +
  " * Re-run `node gen-panzoom.cjs` after changing the asset dump.\n" +
  " */\n\n" +
  "export const PANZOOM_PRESETS = " + JSON.stringify(presets, null, 2) + ";\n\n" +
  "const BY_ID = new Map(PANZOOM_PRESETS.map((p) => [p.id, p]));\n" +
  "export function panZoomPresets() { return PANZOOM_PRESETS; }\n" +
  "export function panZoomById(id) { return BY_ID.get(id) || null; }\n";

fs.writeFileSync(OUT, body, "utf8");
console.log("wrote " + OUT + "  " + (body.length / 1024).toFixed(1) + " KB");
console.log("presets: " + presets.length + " → " + presets.map(p => p.title).join(" | "));
for (const p of presets) {
  const [x, y, w, h] = p.tracks;
  const f = (tr) => tr.keys.map(k => k.v).join("→");
  console.log("  " + p.title.padEnd(22) + " x:" + f(x).padEnd(12) + " y:" + f(y).padEnd(12) +
    " w:" + f(w).padEnd(12) + " h:" + f(h));
}
